#!/usr/bin/env bash
#
# Cleans current directory for unwanted files generated by Chisel.
#
# Files specified in KEEP are not touched.

rm -rf project target

KEEP=".*/\(clean.sh\|Makefile\|.*\.scala\|chisel-dependent.sbt\|build.sbt\)"

find . -mindepth 1 ! -regex ${KEEP} -exec echo "rm -f " {} \; -exec rm -f {} \;
